ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "StockAnalysis" ADD COLUMN IF NOT EXISTS "currency" TEXT NOT NULL DEFAULT 'USD';
ALTER TABLE "StockAnalysis" ADD COLUMN IF NOT EXISTS "priceUSD" DOUBLE PRECISION;
