ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "purchasePrice" DOUBLE PRECISION;
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "purchaseDate"  TIMESTAMP(3);
ALTER TABLE "Stock" ADD COLUMN IF NOT EXISTS "quantity"      DOUBLE PRECISION;
